In [1]:
# Data preprocessing

In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv(r"C:\Users\AMAN JHA\Downloads\Telegram Desktop\bank.csv")

In [4]:
data.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [5]:
data.tail()

age          job  marital  education default  balance housing loan  \
11157   33  blue-collar   single    primary      no        1     yes   no   
11158   39     services  married  secondary      no      733      no   no   
11159   32   technician   single  secondary      no       29      no   no   
11160   43   technician  married  secondary      no        0      no  yes   
11161   34   technician  married  secondary      no        0      no   no   

        contact  day month  duration  campaign  pdays  previous poutcome  \
11157  cellular   20   apr       257         1     -1         0  unknown   
11158   unknown   16   jun        83         4     -1         0  unknown   
11159  cellular   19   aug       156         2     -1         0  unknown   
11160  cellular    8   may         9         2    172         5  failure   
11161  cellular    9   jul       628         1     -1         0  unknown   

      deposit  
11157      no  
11158      no  
11159      no  
11160      no  
11161      no

In [6]:
data.shape

(11162, 17)

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [8]:
data.describe()

age       balance           day      duration      campaign  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948   1528.538524     15.658036    371.993818      2.508421   
std       11.913369   3225.413326      8.420740    347.128386      2.722077   
min       18.000000  -6847.000000      1.000000      2.000000      1.000000   
25%       32.000000    122.000000      8.000000    138.000000      1.000000   
50%       39.000000    550.000000     15.000000    255.000000      2.000000   
75%       49.000000   1708.000000     22.000000    496.000000      3.000000   
max       95.000000  81204.000000     31.000000   3881.000000     63.000000   

              pdays      previous  
count  11162.000000  11162.000000  
mean      51.330407      0.832557  
std      108.758282      2.292007  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       20.750000      1.000000  
max      854.000000     58.000000

In [9]:
data.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [10]:
# here no value is 0 or missing so no need to handle it 

In [11]:
data["job"].unique()

array(['admin.', 'technician', 'services', 'management', 'retired',
       'blue-collar', 'unemployed', 'entrepreneur', 'housemaid',
       'unknown', 'self-employed', 'student'], dtype=object)

In [14]:
data["default"].unique()

array(['no', 'yes'], dtype=object)

In [12]:
data["marital"].unique()

array(['married', 'single', 'divorced'], dtype=object)

In [13]:
data["education"].unique()

array(['secondary', 'tertiary', 'primary', 'unknown'], dtype=object)

In [15]:
data["housing"].unique()

array(['yes', 'no'], dtype=object)

In [16]:
data["loan"].unique()

array(['no', 'yes'], dtype=object)

In [17]:
data["contact"].unique()

array(['unknown', 'cellular', 'telephone'], dtype=object)

In [18]:
data["month"].unique()

array(['may', 'jun', 'jul', 'aug', 'oct', 'nov', 'dec', 'jan', 'feb',
       'mar', 'apr', 'sep'], dtype=object)

In [19]:
data["poutcome"].unique()

array(['unknown', 'other', 'failure', 'success'], dtype=object)

In [20]:
data["deposit"].unique()

array(['yes', 'no'], dtype=object)

In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [22]:
data["job"] = le.fit_transform(data["job"])
data["default"] = le.fit_transform(data["default"])

data["marital"] = le.fit_transform(data["marital"])
data["education"] = le.fit_transform(data["education"])

data["housing"] = le.fit_transform(data["housing"])
data["loan"] = le.fit_transform(data["loan"])

data["contact"] = le.fit_transform(data["contact"])
data["month"] = le.fit_transform(data["month"])

data["poutcome"] = le.fit_transform(data["poutcome"])
data["deposit"] = le.fit_transform(data["deposit"])

In [23]:
data

age  job  marital  education  default  balance  housing  loan  contact  \
0       59    0        1          1        0     2343        1     0        2   
1       56    0        1          1        0       45        0     0        2   
2       41    9        1          1        0     1270        1     0        2   
3       55    7        1          1        0     2476        1     0        2   
4       54    0        1          2        0      184        0     0        2   
...    ...  ...      ...        ...      ...      ...      ...   ...      ...   
11157   33    1        2          0        0        1        1     0        0   
11158   39    7        1          1        0      733        0     0        2   
11159   32    9        2          1        0       29        0     0        0   
11160   43    9        1          1        0        0        0     1        0   
11161   34    9        1          1        0        0        0     0        0   

       day  month  duration  campaign  pdays  previous  poutcome  deposit  
0        5      8      1042         1     -1         0         3        1  
1        5      8      1467         1     -1         0         3        1  
2        5      8      1389         1     -1         0         3        1  
3        5      8       579         1     -1         0         3        1  
4        5      8       673         2     -1         0         3        1  
...    ...    ...       ...       ...    ...       ...       ...      ...  
11157   20      0       257         1     -1         0         3        0  
11158   16      6        83         4     -1         0         3        0  
11159   19      1       156         2     -1         0         3        0  
11160    8      8         9         2    172         5         0        0  
11161    9      5       628         1     -1         0         3        0  

[11162 rows x 17 columns]

In [28]:
x = data.iloc[:,1:17].values
y = data.iloc[:,16].values

In [29]:
type(x)

numpy.ndarray

In [30]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z = one.fit_transform(x[:,1:2]).toarray()

In [31]:
z

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [32]:
x = np.delete(x,1,axis =  1)

In [33]:
x

array([[0, 1, 0, ..., 0, 3, 1],
       [0, 1, 0, ..., 0, 3, 1],
       [9, 1, 0, ..., 0, 3, 1],
       ...,
       [9, 1, 0, ..., 0, 3, 0],
       [9, 1, 0, ..., 5, 0, 0],
       [9, 1, 0, ..., 0, 3, 0]], dtype=int64)

In [34]:
x.shape

(11162, 15)

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [37]:
print(x_train.shape)#trainig input
print(x_test.shape)#testing input
print(y_train.shape)#training output
print(y_test.shape)#testing output

(8929, 15)
(2233, 15)
(8929,)
(2233,)


In [38]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [39]:
x_train

array([[-0.15019091, -0.38014692, -0.12621015, ..., -0.35888264,
         0.52269265, -0.95541123],
       [ 0.15923563, -0.38014692, -0.12621015, ..., -0.35888264,
         0.52269265,  1.04666971],
       [-1.07847054, -1.71387258, -0.12621015, ..., -0.35888264,
         0.52269265,  1.04666971],
       ...,
       [ 2.01579489, -0.38014692, -0.12621015, ..., -0.35888264,
         0.52269265, -0.95541123],
       [-1.38789708, -0.38014692, -0.12621015, ..., -0.35888264,
         0.52269265, -0.95541123],
       [ 0.15923563, -1.71387258, -0.12621015, ..., -0.35888264,
         0.52269265,  1.04666971]])